package palindromes

// DO NOT EDIT THIS FILE OR PACKAGE

type Palindromes interface {
	// Detect will return all strings from the input, words, that meet the criteria of a palindrome.
	Detect(words []string) (palindromes []string)
}





