package state

/// DO NOT EDIT THIS FILE

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

const (
	usernameA = "john"
	usernameB = "jane"
)

func TestState(t *testing.T) {

	store := NewUserStore(usernameA)
	assert.Equal(t, usernameA, store.GetUsername())

	store.SetUsername(usernameB)
	assert.Equal(t, usernameB, store.GetUsername())

}